//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityPicturePlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivityPicturePlugin.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string ActivityPicturePage_Title {
            get {
                return ResourceManager.GetString("ActivityPicturePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string Altitude_HeaderText {
            get {
                return ResourceManager.GetString("Altitude_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btn_Cancel_Text {
            get {
                return ResourceManager.GetString("btn_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btn_OK_Text {
            get {
                return ResourceManager.GetString("btn_OK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string btnCollapseAll_Text {
            get {
                return ResourceManager.GetString("btnCollapseAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string btnExpandAll_Text {
            get {
                return ResourceManager.GetString("btnExpandAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotag.
        /// </summary>
        internal static string btnGeoTag_Text {
            get {
                return ResourceManager.GetString("btnGeoTag_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap btnimage {
            get {
                object obj = ResourceManager.GetObject("btnimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Google Earth.
        /// </summary>
        internal static string btnKML_Text {
            get {
                return ResourceManager.GetString("btnKML_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string btnManImp_Text {
            get {
                return ResourceManager.GetString("btnManImp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time offset.
        /// </summary>
        internal static string btnTimeOffset_Text {
            get {
                return ResourceManager.GetString("btnTimeOffset_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap btnvideo {
            get {
                object obj = ResourceManager.GetObject("btnvideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string commentDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("commentDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        internal static string dateTimeOriginalDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("dateTimeOriginalDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        internal static string equipmentModelDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("equipmentModelDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Data.
        /// </summary>
        internal static string ExifGPS_HeaderText {
            get {
                return ResourceManager.GetString("ExifGPS_HeaderText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GE {
            get {
                object obj = ResourceManager.GetObject("GE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images to Google Earth.
        /// </summary>
        internal static string GoogleEarthExport_Title {
            get {
                return ResourceManager.GetString("GoogleEarthExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options (for selected images).
        /// </summary>
        internal static string goupBoxListOptions_Text {
            get {
                return ResourceManager.GetString("goupBoxListOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS format.
        /// </summary>
        internal static string groupBoxGPSFormat_Text {
            get {
                return ResourceManager.GetString("groupBoxGPSFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Options.
        /// </summary>
        internal static string groupBoxImage_Text {
            get {
                return ResourceManager.GetString("groupBoxImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Options.
        /// </summary>
        internal static string groupBoxVideo_Text {
            get {
                return ResourceManager.GetString("groupBoxVideo_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file.
        /// </summary>
        internal static string ImportControl_addingFile {
            get {
                return ResourceManager.GetString("ImportControl_addingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ImportControl_changeView {
            get {
                return ResourceManager.GetString("ImportControl_changeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import done: A total of.
        /// </summary>
        internal static string ImportControl_importDone1 {
            get {
                return ResourceManager.GetString("ImportControl_importDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have been imported.
        /// </summary>
        internal static string ImportControl_importDone2 {
            get {
                return ResourceManager.GetString("ImportControl_importDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Image.
        /// </summary>
        internal static string ImportControl_importing {
            get {
                return ResourceManager.GetString("ImportControl_importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string ImportControl_in {
            get {
                return ResourceManager.GetString("ImportControl_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan done: A total of.
        /// </summary>
        internal static string ImportControl_scanDone1 {
            get {
                return ResourceManager.GetString("ImportControl_scanDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have been found.
        /// </summary>
        internal static string ImportControl_scanDone2 {
            get {
                return ResourceManager.GetString("ImportControl_scanDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning of.
        /// </summary>
        internal static string ImportControl_scanning {
            get {
                return ResourceManager.GetString("ImportControl_scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching matching activity for.
        /// </summary>
        internal static string ImportControl_searchingActivity {
            get {
                return ResourceManager.GetString("ImportControl_searchingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        internal static string labelImageSize_Text {
            get {
                return ResourceManager.GetString("labelImageSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time Stamp.
        /// </summary>
        internal static string ModifyTimeStamp_Text {
            get {
                return ResourceManager.GetString("ModifyTimeStamp_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Source.
        /// </summary>
        internal static string photoSourceDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("photoSourceDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string pictureAlbumToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pictureAlbumToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string pictureListToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pictureListToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceID.
        /// </summary>
        internal static string referenceIDDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("referenceIDDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string SettingsPageControl_lblQuality_Text {
            get {
                return ResourceManager.GetString("SettingsPageControl_lblQuality_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string thumbnailDataGridViewImageColumn_HeaderText {
            get {
                return ResourceManager.GetString("thumbnailDataGridViewImageColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string titleDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("titleDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string toolStripButtonPause_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPause_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string toolStripButtonPlay_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPlay_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string toolStripButtonStop_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonStop_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected images.
        /// </summary>
        internal static string tooltip_OnlySelectedImages {
            get {
                return ResourceManager.GetString("tooltip_OnlySelectedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeImage_HeaderText {
            get {
                return ResourceManager.GetString("TypeImage_HeaderText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string waypointDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("waypointDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
    }
}
